//
//  LSDeviceProfiles.h
//  LSBluetooth-Library
//
//  Created by lifesense on 15/8/7.
//  Copyright (c) 2015年 Lifesense. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "LSDeviceInfo.h"
#import <CoreBluetooth/CBUUID.h>

FOUNDATION_EXPORT NSString *const SERVICE_UUID_A2_BLOOD_PRESSURE;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_A3_BLOOD_PRESSURE;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_COMMAND_START_BLOOD_PRESSURE;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_A3_1_BLOOD_PRESSURE;

FOUNDATION_EXPORT NSString *const SERVICE_UUID_KITCHEN_SCALE;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_HEIGHT_SCALE;

FOUNDATION_EXPORT NSString *const SERVICE_UUID_A2_WEIGHT_SCALE;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_A3_FAT_SCALE;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_A3_SALTER_FAT_SCALE;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_GENERIC_FAT_SCALE;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_A3_1_FAT_SCALE;

FOUNDATION_EXPORT NSString *const SERVICE_UUID_A2_PEDOMETER;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_A4_PEDOMETER;
FOUNDATION_EXPORT NSString *const SERVICE_UUID_WECHAT_PEDOMETER;

FOUNDATION_EXPORT NSString *const PROTOCOL_TYPE_A2;
FOUNDATION_EXPORT NSString *const PROTOCOL_TYPE_A3;
//FOUNDATION_EXPORT NSString *const PROTOCOL_TYPE_A4;
FOUNDATION_EXPORT NSString *const PROTOCOL_TYPE_A3_1;

FOUNDATION_EXPORT NSString *const PROTOCOL_TYPE_GENERIC_FAT;
FOUNDATION_EXPORT NSString *const PROTOCOL_TYPE_KITCHEN;
FOUNDATION_EXPORT NSString *const PROTOCOL_TYPE_BLOOD_PRESSURE_COMMAND_START;
FOUNDATION_EXPORT NSString *const PROTOCOL_TYPE_WECHAT;
FOUNDATION_EXPORT NSString *const PROTOCOL_TYPE_GLUCOSE_METER;


FOUNDATION_EXPORT NSString *const KEY_WEIGHT_SCALE_USER_INFO;
FOUNDATION_EXPORT NSString *const KEY_WEIGHT_SCALE_VIBRATION_VOICE;
FOUNDATION_EXPORT NSString *const KEY_PEDOMETER_ALARM_CLOCK;
FOUNDATION_EXPORT NSString *const KEY_PEDOMETER_USER_INFO;

//device type key
FOUNDATION_EXPORT NSString *const KEY_DEVICE_TYPE_WEIGHT_SCALE;
FOUNDATION_EXPORT NSString *const KEY_DEVICE_TYPE_FAT_SCALE;
FOUNDATION_EXPORT NSString *const KEY_DEVICE_TYPE_HEIGHT_RULER;
FOUNDATION_EXPORT NSString *const KEY_DEVICE_TYPE_PEDOMETER;
FOUNDATION_EXPORT NSString *const KEY_DEVICE_TYPE_WAIST_RULER;
FOUNDATION_EXPORT NSString *const KEY_DEVICE_TYPE_GLUCOSE_METER;
FOUNDATION_EXPORT NSString *const KEY_DEVICE_TYPE_THERMOMETER;
FOUNDATION_EXPORT NSString *const KEY_DEVICE_TYPE_SPHYGMOMAN_METER;
FOUNDATION_EXPORT NSString *const KEY_DEVICE_TYPE_KITCHEN_SCALE;

@interface LSDeviceProfiles : NSObject


+(NSString *)getProtocolTypeFromServices:(NSString *)serviceUUID;

+(LSDeviceType)getDeviceTypeFromServices:(NSString *)serviceUUID;

+(BOOL)checkingDeviceInfoCharacteristic:(uint16_t)uuidValue;

+(NSArray *)getGattServicesFromDeviceType:(NSArray *)deviceTypes;

+(NSInteger)getServiceUuidByDeviceType:(LSDeviceType)deviceType protocolType:(NSString *)protocolType;

@end
